services:
  soar:
    build: .
    container_name: soar-ai-auto

    ports:
      - "8000:8000"

    volumes:
      - /var/lib/docker/volumes/soc-server_wazuh_logs/_data:/var/ossec/logs:ro
      - ./data:/app/data
    restart: unless-stopped
