services:
  suricata:
    image: jasonish/suricata:latest
    container_name: ubuntu-suricata
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_NICE
    volumes:
      - ./suricata/logs:/var/log/suricata
      - ./suricata/rules/local.rules:/etc/suricata/rules/local.rules
    command: -i enp2s0 -S /etc/suricata/rules/local.rules
    restart: unless-stopped
